# Generated by Django 5.0.2 on 2024-02-19 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking_app', '0006_alter_history_modified_at_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 0, 20, 804533, tzinfo=datetime.timezone.utc)),
        ),
    ]
