# Generated by Django 5.0.2 on 2024-02-19 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking_app', '0007_alter_history_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 2, 44, 138222, tzinfo=datetime.timezone.utc)),
        ),
    ]
